meta_title: "Super-Battle - Who'll win the Instagram Battle?"
meta_description: "Super-battle is a fun app which allows Instagram users to compare their accounts."
meta_image: "super-battle-sharing.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
