meta_title: "Super-Battle, a fun web-app to compare Instagram accounts"
meta_description: "Super-battle is a fun app which allows Instagram users to compare their accounts."
meta_image: "super-battle-sharing.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@SupaBattle" # indispensable pour les Twittxer Cards
