meta_title: "Titre générique"
meta_description: "Description générique."
meta_image: "super-battle-sharing.jpeg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
