meta_title: "Super-Battle"
meta_description: "Super-battle is a fun app which allows Instagram users to compare their accounts."
meta_image: "super-battle-sharing.jpeg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
